---
version: "3"
services:
  lx-music:
    container_name: lx-music
    image: lyswhut/lx-music-sync-server:v2.1.0
    ports:
      - "9527:9527"
    environment:
      - BIND_IP=0.0.0.0
      - LX_USER_chaney=lx-chaney
    restart: always
    volumes:
      - ./lx-data/:/server/data/data
