---
version: "3.3"
services:
  adguardhome:
    container_name: adguardhome
    restart: unless-stopped
    volumes:
      - ./adguard/adguardhome/work:/opt/adguardhome/work
      - ./adguard/adguardhome/conf:/opt/adguardhome/conf
    network_mode: host
    image: adguard/adguardhome
