Host chaney-pve.local
    Hostname chaney-pve.local
    User root

Host chaney-dev.local
    Hostname chaney-dev.local

Host chaney-dev.ts
    Hostname chaney-dev.tail0680a.ts.net

Host chaney-wk1.local
    Hostname chaney-wk1.local

Host chaney-wk1.ts
    Hostname chaney-wk1.tail0680a.ts.net

Host chaney-*
    CheckHostIP no
    StrictHostKeyChecking no
    UserKnownHostsFile=/dev/null
    User chaney
    ForwardAgent yes
