Host chaney-pve.local
    Hostname chaney-pve.local
    User root

Host chaney-* *.local
    CheckHostIP no
    StrictHostKeyChecking no
    UserKnownHostsFile=/dev/null
    User chaney
    ForwardAgent yes

Host chaney-dev.local
    Hostname chaney-dev.local
Host chaney-dev.tsc
    Hostname 100.126.203.25
Host chaney-wk1.local
    Hostname chaney-wk1.local
